spring:

  application:
    name: sensor-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smart_home?useSSL=false&serverTimezone=UTC
    username: root
    password:

  kafka:
    bootstrap-servers: localhost:9092

  jpa:
    hibernate:
      ddl-auto: update          # або validate/create по бажанню
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true              # опційно, покаже SQL у логи

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8084